Models/CSProductsViewModel.cs
using System.ComponentModel;

namespace CyberGuardian360.Models
{
    public class CSProductsViewModel
    {
        public int Id { get; set; }

        [DisplayName("Product Name")]
        public string? ProductName { get; set; }

        public double ProductCost { get; set; }

        [DisplayName("Product Rating")]
        public double ProductRating { get; set; }

        [DisplayName("Product Image")]
        public string? ImageUrl { get; set; }

        [DisplayName("Product Description")]
        public string? ProductDescription { get; set; }
    }
}

Models/EFDBContext/CSProducts.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace CyberGuardian360.Models.EFDBContext
{
    public class CSProducts
    {
        public enum CSCategories
        {
            [Description("Antivirus Software")]
            AntivirusSoftware = 1,

            [Description("Firewall Solutions")]
            FirewallSolutions = 2,

            [Description("Data Encryption Tools")]
            DataEncryptionTools = 3,
        }
        public int Id { get; set; }

        [DisplayName("Product Name")]
        [Required]
        public string ProductName { get; set; }

        [Required]
        [DisplayName("Product Cost")]
        public double ProductCost { get; set; }

        [Required]
        [DisplayName("Product Rating")]
        public double ProductRating { get; set; }

        [DisplayName("Product Description")]
        public string ProductDescription { get; set; }

        [DisplayName("Product Image")]
        public string? ImageUrl { get; set; }

        [DisplayName("Product Category")]
        [Required]
        public CSCategories ProductCategoryId { get; set; }

        public DateTime CreatedDate { get; set; }

        public DateTime ModifiedDate { get; set; }
    }
}

Controllers/CSProductsController.cs
using CyberGuardian360.DBContext;
using CyberGuardian360.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CyberGuardian360.Controllers
{
    public class CSProductsController : Controller
    {
        private readonly CyberGuardian360DbContext _context;
        public CSProductsController(CyberGuardian360DbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult Index()
        {
            TempData["NoProducts"] = null;
            var products = _context.CSProducts.ToList();

            if (products.Count == 0)
            {
                TempData["NoProducts"] = "Currently no products available.";
                return View();
            }

            Filter filter = new Filter();
            List<CSProductsViewModel> productViewModels = new List<CSProductsViewModel>();

            foreach (var product in products)
            {
                CSProductsViewModel productsModel = new CSProductsViewModel()
                {
                    ImageUrl = product.ImageUrl,
                    ProductName = product.ProductName,
                    ProductCost = product.ProductCost,
                    ProductRating = product.ProductRating,
                    ProductDescription = product.ProductDescription,
                    Id = product.Id,
                };

                productViewModels.Add(productsModel);
            }
            filter.CSProductsViewModel = productViewModels;
            var list = new List<CheckboxModel>
            {
                new CheckboxModel{Id = 1, Name = "Anti Virus Software", Checked = false},
                new CheckboxModel{Id = 2, Name = "Firewall Solutions", Checked = false},
                new CheckboxModel{Id = 3, Name = "Data Encryption Tools", Checked = false}
            };
            filter.CheckBoxes = list;

            return View(filter);
        }

        [HttpGet]
        public async Task<IActionResult> GetProductsByFilter(int[] chkCategories)
        {

            if (chkCategories.Length > 0)
            {
                var products = await _context.CSProducts
                    .Where(s => chkCategories.Contains((int)s.ProductCategoryId)).ToListAsync();

                if (products.Count == 0)
                {
                    TempData["NoProducts"] = $"No products available for category.";
                    return RedirectToAction("Index");
                }

                var productviewmodels = products.Select(product => new CSProductsViewModel
                {
                    ImageUrl = product.ImageUrl,
                    ProductName = product.ProductName,
                    ProductCost = product.ProductCost,
                    ProductRating = product.ProductRating,
                    Id = product.Id
                }).ToList();

                Filter filter = new Filter();
                filter.CSProductsViewModel = productviewmodels;
                var list = new List<CheckboxModel>
                {
                    new CheckboxModel{Id = 1, Name = "Anti Virus Software"},
                    new CheckboxModel{Id = 2, Name = "Firewall Solutions"},
                    new CheckboxModel{Id = 3, Name = "Data Encryption Tools"}
                };

                foreach (var item in list)
                {
                    if (chkCategories.Contains(item.Id))
                    {
                        item.Checked = true;
                    }
                    else
                    {
                        item.Checked = false;
                    }
                }
                filter.CheckBoxes = list;

                return PartialView("ProductListPartialView", filter);
            }

            return RedirectToAction("Index");
        }
    }
}

Views/CSProducts/Index.cshtml
@model CyberGuardian360.Models.Filter
@using Microsoft.AspNetCore.Identity
@inject SignInManager<CyberGuardian360.Models.EFDBContext.UserRegistration> SignInManager

@if (SignInManager.IsSignedIn(User))
{
    <div id="productListContainer">
        @await Html.PartialAsync("ProductListPartialView", Model)
    </div>
}
else
{
    <div class="row g-3 col-form-label-lg paddingtop3rem">You are logged out. Please sign In.</div>
}

@section Scripts {
    <script>
        $(document).ready(function () {
            $('#frmCategories').submit(function (e) {
                e.preventDefault();
                var selectedCategories = [];
                $('input[name="chkCategories"]:checked').each(function () {
                    selectedCategories.push($(this).val());
                });
                $.ajax({
                    url: '@Url.Action("GetProductsByFilter", "CSProducts")',
                    type: 'GET',
                    data: { 'chkCategories': selectedCategories },
                    traditional: true,
                    success: function (result) {
                        $('#productListContainer').html(result);
                    },
                    error: function () {
                        alert('Error occurred while applying filter.');
                    }
                });
            });
        });
    </script>
}

Views/CSProducts/ProductListPartialView.cshtml
@model CyberGuardian360.Models.Filter

@{
    ViewData["Title"] = "CS Products";
    // Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (Model != null)
{
    <table class="w100">
        <tr>
            <td class="w20 valign-top">
                <div>
                    <p class="t-center"><b>Apply Filters</b></p>
                    <hr>
                    <p><b>Category:</b></p>
                    <form id="frmCategories">
                        @foreach (var checkbox in Model.CheckBoxes)
                        {
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" id="@checkbox.Id" value="@checkbox.Id" name="chkCategories">
                                <label class="form-check-label" for="@checkbox.Id">@checkbox.Name</label>
                            </div>
                        }
                        <hr>
                        <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                            <button type="submit" class="btn btn-sm cust_btn" id="btnfilter">Apply Filter</button>
                        </div>
                    </form>
                </div>
            </td>
            <td class="w80">
                <div class="container">
                    <p class="t-center" style="font-size:20px"><b>Products</b></p>
                    <div class="row mt-5 mb-3">
                        @if (Model.CSProductsViewModel is { Count: > 0 })
                        {
                            @foreach (var product in Model.CSProductsViewModel)
                            {
                                <div class="col-sm-12 mb-4">
                                    <div class="card">
                                        <table border="0">
                                            <tr>
                                                <td style="width:15%">
                                                    <img src="product_images/@product.ImageUrl" class="card-img-top" alt="Product Image" style="height:150px;width:150px">
                                                </td>
                                                <td style="width:65%">
                                                    <div class="card-body">
                                                        <h5 class="card-title">@product.ProductName</h5>
                                                        <p class="card-text">Price: £@product.ProductCost</p>
                                                        <p class="card-text">Rating: @product.ProductRating</p>
                                                        <p class="card-text">Description: @product.ProductDescription</p>
                                                    </div>
                                                </td>
                                                <td style="width:25%; text-align:right; padding-right:1rem;">
                                                    <a asp-controller="Cart" asp-action="AddToCart" asp-route-id="@product.Id" class="btn btn-primary cust_btn">Add to Cart</a>
                                                </td>
                                            </tr>
                                        </table>
                                    </div>
                                </div>
                            }
                        }
                        else
                        {
                            <div>No products available.</div>
                        }
                    </div>
                </div>
            </td>
        </tr>
    </table>
}
else
{
    <div class="row g-3 col-form-label-lg paddingtop3rem">No products available. Please contact admin.</div>
}